SalvemosVidasApp/config/routes.rb
Rails.application.routes.draw do
  
  #Agrega el recurso de comentarios a los post en el foro
  resources :forum_posts do
    resources :commentaries, only: [:create, :destroy, :update]
  end
  resources :questions
  resources :paragraphs
  resources :images
  resources :practices
  resources :slides
  resources :lessons
  devise_for :users, controllers: {
  	omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  resources :usuarios, as: :users, only: [:show,:update]

  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  get "/lessons/category/:category(.:format)", to: "lessons#category"
  get "/practices/category/:category(.:format)", to: "practices#category"
  #admnistrators
  get "/data_users", to: "users/administrators#index"
  get "/data_users/new", to: "users/administrators#new"
  post "/data_users/create", to: "users/administrators#create"
  delete "/data_users/:id(.:format)", :to => "users/administrators#destroy"

  #data_lessons
  get "/data_lessons/new" , to: "data_lessons#new"
  get "/data_lessons/:category(.:format)", to: "data_lessons#lessons"
  get "/data_lessons/info/:id(.:format)", to: "data_lessons#show"
  post "/data_lessons" , to: "data_lessons#create"

  root "main#home"

  # 1 Se envia una petición a facebook
  # 2 Facebook retorna a la aplicación con el callback_url que se le pase
  # 3 Procesar la información de facebook
  # 4 Autenticar nuevo usuario o crearlo.
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SalvemosVidasApp/app/models/paragraph.rb
# == Schema Information
#
# Table name: paragraphs
#
#  id          :bigint(8)        not null, primary key
#  information :string
#  slide_id    :bigint(8)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Paragraph < ApplicationRecord
  belongs_to :slide
end

SalvemosVidasApp/app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  before_action :set_paragraph, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /paragraphs
  # GET /paragraphs.json
  def index
    @paragraphs = Paragraph.all
  end

  # GET /paragraphs/1
  # GET /paragraphs/1.json
  def show
  end

  # GET /paragraphs/new
  def new
    @paragraph = Paragraph.new
  end

  # GET /paragraphs/1/edit
  def edit
  end

  # POST /paragraphs
  # POST /paragraphs.json
  def create
    @paragraph = Paragraph.new(paragraph_params)

    print "Parrafos guardar: ",@slide.paragraphs

    respond_to do |format|
      if @paragraph.save
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully created.' }
        format.json { render :show, status: :created, location: @paragraph }
      else
        format.html { render :new }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paragraphs/1
  # PATCH/PUT /paragraphs/1.json
  def update
    respond_to do |format|
      if @paragraph.update(paragraph_params)
        format.html { redirect_to @paragraph, notice: 'Paragraph was successfully updated.' }
        format.json { render :show, status: :ok, location: @paragraph }
      else
        format.html { render :edit }
        format.json { render json: @paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paragraphs/1
  # DELETE /paragraphs/1.json
  def destroy
    @paragraph.destroy
    respond_to do |format|
      format.html { redirect_to paragraphs_url, notice: 'Paragraph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paragraph
      @paragraph = Paragraph.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paragraph_params
      params.require(:paragraph).permit(:information, :slide_id)
    end
end

SalvemosVidasApp/app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

SalvemosVidasApp/app/views/paragraphs/_form.html.erb
<%= form_with(model: paragraph, local: true) do |form| %>
  <% if paragraph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paragraph.errors.count, "error") %> prohibited this paragraph from being saved:</h2>

      <ul>
      <% paragraph.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_field :information %>
  </div>

  <div class="field">
    <%= form.label :slide_id %>
    <%= form.text_field :slide_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

SalvemosVidasApp/app/views/paragraphs/edit.html.erb
<h1>Editing Paragraph</h1>

<%= render 'form', paragraph: @paragraph %>

<%= link_to 'Show', @paragraph %> |
<%= link_to 'Back', paragraphs_path %>

SalvemosVidasApp/app/views/paragraphs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paragraphs</h1>

<table>
  <thead>
    <tr>
      <th>Information</th>
      <th>Slide</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paragraphs.each do |paragraph| %>
      <tr>
        <td><%= paragraph.information %></td>
        <td><%= paragraph.slide %></td>
        <td><%= link_to 'Show', paragraph %></td>
        <td><%= link_to 'Edit', edit_paragraph_path(paragraph) %></td>
        <td><%= link_to 'Destroy', paragraph, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paragraph', new_paragraph_path %>

SalvemosVidasApp/app/views/paragraphs/new.html.erb
<h1>New Paragraph</h1>

<%= render 'form', paragraph: @paragraph %>

<%= link_to 'Back', paragraphs_path %>

SalvemosVidasApp/app/views/paragraphs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Information:</strong>
  <%= @paragraph.information %>
</p>

<p>
  <strong>Slide:</strong>
  <%= @paragraph.slide %>
</p>

<%= link_to 'Edit', edit_paragraph_path(@paragraph) %> |
<%= link_to 'Back', paragraphs_path %>