SalvemosVidasApp/config/routes.rb
Rails.application.routes.draw do
  
  #Agrega el recurso de comentarios a los post en el foro
  resources :forum_posts do
    resources :commentaries, only: [:create, :destroy, :update]
  end
  resources :questions
  resources :paragraphs
  resources :images
  resources :practices
  resources :slides
  resources :lessons
  devise_for :users, controllers: {
  	omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  resources :usuarios, as: :users, only: [:show,:update]

  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  get "/lessons/category/:category(.:format)", to: "lessons#category"
  get "/practices/category/:category(.:format)", to: "practices#category"
  #admnistrators
  get "/data_users", to: "users/administrators#index"
  get "/data_users/new", to: "users/administrators#new"
  post "/data_users/create", to: "users/administrators#create"
  delete "/data_users/:id(.:format)", :to => "users/administrators#destroy"

  #data_lessons
  get "/data_lessons/new" , to: "data_lessons#new"
  get "/data_lessons/:category(.:format)", to: "data_lessons#lessons"
  get "/data_lessons/info/:id(.:format)", to: "data_lessons#show"
  post "/data_lessons" , to: "data_lessons#create"

  root "main#home"

  # 1 Se envia una petición a facebook
  # 2 Facebook retorna a la aplicación con el callback_url que se le pase
  # 3 Procesar la información de facebook
  # 4 Autenticar nuevo usuario o crearlo.
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SalvemosVidasApp/app/models/commentary.rb
# == Schema Information
#
# Table name: commentaries
#
#  id            :bigint(8)        not null, primary key
#  datail        :string
#  user_id       :bigint(8)
#  forum_post_id :bigint(8)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Commentary < ApplicationRecord
  belongs_to :user
  belongs_to :forum_post
end

SalvemosVidasApp/app/controllers/commentaries_controller.rb
class CommentariesController < ApplicationController
  before_action :set_commentary, only: [:show, :edit, :update, :destroy]
  before_action :set_article
  before_action :authenticate_user!
  # GET /commentaries
  # GET /commentaries.json
  def index
    @commentaries = Commentary.all
  end

  # GET /commentaries/1
  # GET /commentaries/1.json
  def show
  end

  # GET /commentaries/new
  def new
    @commentary = Commentary.new
  end

  # GET /commentaries/1/edit
  def edit
  end

  # POST /commentaries
  # POST /commentaries.json
  def create
    @commentary = current_user.commentaries.new(commentary_params)
    @commentary.forum_post = @forum_post

    puts "Aqui esto1"
    respond_to do |format|
      puts @commentary.to_json
      if @commentary.save
        puts "Aqui esto2"
        format.html { redirect_to @commentary.forum_post, notice: 'Commentary was successfully created.' }
        format.json { render :show, status: :created, location: @commentary }
      else
        puts "Aqui esto3"
        format.html { render :new }
        format.json { render json: @commentary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commentaries/1
  # PATCH/PUT /commentaries/1.json
  def update
    respond_to do |format|
      if @commentary.update(commentary_params)
        format.html { redirect_to @commentary.forum_post, notice: 'Commentary was successfully updated.' }
        format.json { render :show, status: :ok, location: @commentary }
      else
        format.html { render :edit }
        format.json { render json: @commentary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commentaries/1
  # DELETE /commentaries/1.json
  def destroy
    @commentary.destroy
    respond_to do |format|
      format.html { redirect_to @forum_post, notice: 'Commentary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @forum_post = ForumPost.find(params[:forum_post_id])
      puts "obtuve el parametro",@forum_post
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_commentary
      @commentary = Commentary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commentary_params
      params.require(:commentary).permit(:datail)
    end
end

SalvemosVidasApp/app/helpers/commentaries_helper.rb
module CommentariesHelper
end

SalvemosVidasApp/app/views/commentaries/_form.html.erb
<%= form_with(model: [@forum_post, @commentary], remote: true) do |form| %>
  <% if @commentary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commentary.errors.count, "error") %> prohibited this commentary from being saved:</h2>

      <ul>
      <% @commentary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :"Deje su comentario:", class:"control-label col-sm-2"%>
    <div class="col-sm-10">
      <%= form.text_area :datail, class:"form-control", rows:5,placeholder:"Ingrese su comentario..." %>
    </div>
  </div>

  <div class="col-sm-offset-2 col-sm-10" style="margin-top: 10px;">
        <%= form.submit :Comentar, class:"btn" %>
  </div>

  <br>
<% end %>

SalvemosVidasApp/app/views/commentaries/edit.html.erb
<h1>Editing Commentary</h1>

<%= render 'form', commentary: @commentary %>

<%= link_to 'Show', @commentary %> |
<%= link_to 'Back', commentaries_path %>

SalvemosVidasApp/app/views/commentaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Commentaries</h1>

<table>
  <thead>
    <tr>
      <th>Datail</th>
      <th>User</th>
      <th>Forum post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commentaries.each do |commentary| %>
      <tr>
        <td><%= commentary.datail %></td>
        <td><%= commentary.user %></td>
        <td><%= commentary.forum_post %></td>
        <td><%= link_to 'Show', commentary %></td>
        <td><%= link_to 'Edit', edit_commentary_path(commentary) %></td>
        <td><%= link_to 'Destroy', commentary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commentary', new_commentary_path %>

SalvemosVidasApp/app/views/commentaries/new.html.erb
<h1>New Commentary</h1>

<%= render 'form', commentary: @commentary %>

<%= link_to 'Back', forum_post_commentaries_path %>

SalvemosVidasApp/app/views/commentaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datail:</strong>
  <%= @commentary.datail %>
</p>

<p>
  <strong>User:</strong>
  <%= @commentary.user %>
</p>

<p>
  <strong>Forum post:</strong>
  <%= @commentary.forum_post %>
</p>

<%= link_to 'Edit', edit_commentary_path(@commentary) %> |
<%= link_to 'Back', commentaries_path %>