SalvemosVidasApp/config/routes.rb
Rails.application.routes.draw do
  
  #Agrega el recurso de comentarios a los post en el foro
  resources :forum_posts do
    resources :commentaries, only: [:create, :destroy, :update]
  end
  resources :questions
  resources :paragraphs
  resources :images
  resources :practices
  resources :slides
  resources :lessons
  devise_for :users, controllers: {
  	omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  resources :usuarios, as: :users, only: [:show,:update]

  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  get "/lessons/category/:category(.:format)", to: "lessons#category"
  get "/practices/category/:category(.:format)", to: "practices#category"
  #admnistrators
  get "/data_users", to: "users/administrators#index"
  get "/data_users/new", to: "users/administrators#new"
  post "/data_users/create", to: "users/administrators#create"
  delete "/data_users/:id(.:format)", :to => "users/administrators#destroy"

  #data_lessons
  get "/data_lessons/new" , to: "data_lessons#new"
  get "/data_lessons/:category(.:format)", to: "data_lessons#lessons"
  get "/data_lessons/info/:id(.:format)", to: "data_lessons#show"
  post "/data_lessons" , to: "data_lessons#create"

  root "main#home"

  # 1 Se envia una petición a facebook
  # 2 Facebook retorna a la aplicación con el callback_url que se le pase
  # 3 Procesar la información de facebook
  # 4 Autenticar nuevo usuario o crearlo.
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SalvemosVidasApp/app/controllers/data_lessons_controller.rb
class DataLessonsController < ApplicationController
	before_action :set_lessons, only: [:lessons]
	before_action :set_lesson, only: [:show]
	before_action :authenticate_user!
	#Muestra la leccion
	def show

	end
	#Muestra todas las lecciones
	def lessons
	end

	def new
    @lesson = Lesson.new
  end

	def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

	private									
	  def set_lessons
	  	if (params[:category] == "all")
	  		@lessons = Lesson.all.order("created_at desc")
	  	else
	  		@lessons = Lesson.where(category: params[:category]).order("created_at desc")
	  	end
	  end

	  def set_lesson
	  	@lesson = Lesson.find(params[:id])
	  end

end

SalvemosVidasApp/app/helpers/data_lessons_helper.rb
module DataLessonsHelper
end

SalvemosVidasApp/app/views/data_lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-horizontal">
    <div class="form-group">
      <%= form.label :Nombre, class:"control-label col-sm-2"%>
      <div class="col-sm-10">
        <%= form.text_field :name, class:"form-control",placeholder:"Ingrese el dato..." %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :Descripción, class:"control-label col-sm-2"%>
      <div class="col-sm-10">
        <%= form.text_area :description, class:"form-control", rows:5,placeholder:"Ingrese el dato..." %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :Categoria, class:"control-label col-sm-2"%>
      <div class="col-sm-10">
        <%= form.text_field :category, class:"form-control",placeholder:"Ingrese el dato..." %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :user_id, class:"control-label col-sm-2"%>
      <div class="col-sm-10">
        <%= form.text_field :user_id, class:"form-control",placeholder:"Ingrese el dato..." %>
      </div>
    </div>

    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <%= form.submit "Agregar Lección" , class:"btn"%>
      </div>
    </div>

  </div>

<% end %>

SalvemosVidasApp/app/views/data_lessons/lessons.html.erb
<p id="notice"><%= notice %></p>

<div class="container" style="margin-top: -20px; width: 95%; height: 90%;">
  <div class="panel">
    <div class="panel-body">
      <div class="row">
        <div class="panel col-sm-3" style="padding-top:10px;padding-bottom:10px;background-color:#fafafa; margin-right: 20px; margin-left: 30px;">
          <h4 align="center" style="font-family: 'Roboto'; font-size: 18px;">Temas sobre Lecciones:</h4>
          <!--Van las etiquetas: -->
          <div class="row conteiner-tema">
            <%= image_tag("Temas/cortada.png", class:"image-tema") %>
            <%= link_to 'Cortadas', category: "cortadas" %>
          </div>
          <div class="row conteiner-tema">
            <%= image_tag("Temas/quimica.png", class:"image-tema") %>
            <%= link_to 'Accidente Químico', category: "accidente_quimico" %>
          </div>
          <div class="row conteiner-tema">
            <%= image_tag("Temas/quemadura.png", class:"image-tema") %>
            <%= link_to 'Quemaduras', category: "quemaduras" %>
          </div>
          <div class="row conteiner-tema">
            <%= image_tag("Temas/veneno.png", class:"image-tema") %>
            <%= link_to 'Envenenamiento', category: "envenenamiento" %>
          </div>
          <div class="row conteiner-tema">
            <%= image_tag("Temas/sentidos.png", class:"image-tema") %>
            <%= link_to 'Afectación Sentido', category: "afectacion_sentido" %>
          </div>
          <div class="row conteiner-tema">
            <%= image_tag("Temas/accidente.png", class:"image-tema") %>
            <%= link_to 'Accidente', category: "accidente" %>
          </div>
          <div class="row conteiner-tema">
            <%= image_tag("Temas/prevencion.png", class:"image-tema") %>
            <%= link_to 'Prevención', category: "prevencion" %>
          </div>
        </div>

        <div id="panelPrincipal" class="panel col-sm-8" style="padding-top:10px;padding-bottom:10px; margin-right: 20px;margin-left: 20px; background-color: #fafafa;">

          <div class="row">
            <div style="float: left; margin-left: 20px;">
              <form class="form-inline" action="/action_page.php">
                <div class="form-group">
                  <label for="email">Buscar:</label>
                  <input type="text" class="form-control" id="usr" style="width: 70%">
                </div>
              </form>   
            </div>
            <div align="right" style="float: right;margin-right: 20px;">
              <%= link_to 'Crear Nueva Lección', new_lesson_path, class:"btn"%>
            </div>

          </div>
          
          <br>

          <div id="divBuscador">

            <% @lessons.each do |lesson| %>
              <div style="background: #fff; width: 100%;padding-left: 10px; padding-top: 5px;">
              <div>
                <a href="/data_lessons/info/<%= lesson.id %>"><%= lesson.name %></a>
              </div>
              <div>
                <p><%= lesson.description %></p>
              </div>
              <div>
                <p>Publicada por: <%= lesson.user.username %> el <%= lesson.created_at %> </p>
              </div>
            </div>
            <br>
          <% end %>

          </div>

      </div>
    </div>
  </div>
</div>

SalvemosVidasApp/app/views/data_lessons/new.html.erb
<% if signed_in? %>
	<h2 align="center">Creación de Lección</h2>

	<%= render 'form', lesson: @lesson %>

	<div class="col-sm-offset-2 col-sm-10">
        <%= button_to 'Volver', lessons_path, class:"btn" , method: :get %>
    </div>

<% else %>
    <div class="alert alert-danger panel-ancho">
      <h4>Error!</h4>
      <p>Necesita iniciar sesión para acceder a esta dirección.</p>
    </div>
<% end %>

SalvemosVidasApp/app/views/data_lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lesson.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lesson.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @lesson.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @lesson.user %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', "/data_lessons/all" %>