SalvemosVidasApp/config/routes.rb
Rails.application.routes.draw do
  
  #Agrega el recurso de comentarios a los post en el foro
  resources :forum_posts do
    resources :commentaries, only: [:create, :destroy, :update]
  end
  resources :questions
  resources :paragraphs
  resources :images
  resources :practices
  resources :slides
  resources :lessons
  devise_for :users, controllers: {
  	omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations"
  }

  resources :usuarios, as: :users, only: [:show,:update]

  post "/custom_sign_up", to: "users/omniauth_callbacks#custom_sign_up"
  get "/lessons/category/:category(.:format)", to: "lessons#category"
  get "/practices/category/:category(.:format)", to: "practices#category"
  #admnistrators
  get "/data_users", to: "users/administrators#index"
  get "/data_users/new", to: "users/administrators#new"
  post "/data_users/create", to: "users/administrators#create"
  delete "/data_users/:id(.:format)", :to => "users/administrators#destroy"

  #data_lessons
  get "/data_lessons/new" , to: "data_lessons#new"
  get "/data_lessons/:category(.:format)", to: "data_lessons#lessons"
  get "/data_lessons/info/:id(.:format)", to: "data_lessons#show"
  post "/data_lessons" , to: "data_lessons#create"

  root "main#home"

  # 1 Se envia una petición a facebook
  # 2 Facebook retorna a la aplicación con el callback_url que se le pase
  # 3 Procesar la información de facebook
  # 4 Autenticar nuevo usuario o crearlo.
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SalvemosVidasApp/app/models/slide.rb
# == Schema Information
#
# Table name: slides
#
#  id                  :bigint(8)        not null, primary key
#  title               :string
#  tipo                :string
#  lesson_id           :bigint(8)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  parrafo1            :text
#  parrafo2            :text
#  parrafo3            :text
#  imagen1             :text
#  imagen2             :text
#  imagen3             :text
#  image1_file_name    :string
#  image1_content_type :string
#  image1_file_size    :integer
#  image1_updated_at   :datetime
#  image2_file_name    :string
#  image2_content_type :string
#  image2_file_size    :integer
#  image2_updated_at   :datetime
#  image3_file_name    :string
#  image3_content_type :string
#  image3_file_size    :integer
#  image3_updated_at   :datetime
#

class Slide < ApplicationRecord
	has_attached_file :image1, styles: { medium: "350x350>", small: "225x225>" }, default_url: "/images/:style/missing.jpeg"
	has_attached_file :image2, styles: { medium: "350x350>", small: "225x225>" }, default_url: "/images/:style/missing.jpeg"
	has_attached_file :image3, styles: { medium: "350x350>", small: "225x225>" }, default_url: "/images/:style/missing.jpeg"
  
  validates_attachment_content_type :image1, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :image2, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :image3, content_type: /\Aimage\/.*\z/

  belongs_to :lesson

end

SalvemosVidasApp/app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_lesson, only: [:new]
  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    @slide.lesson_id = @@lesson_id
   
    respond_to do |format|
      if @slide.save
        format.html { redirect_to new_slide_path(lesson_id: @slide.lesson_id), notice: 'Slide was successfully created.' }
      else
        format.html { render :new }
      end
    end
    
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    def set_lesson
      @@lesson_id = params[:lesson_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:title, :tipo, :parrafo1, :parrafo2, :parrafo3, :image1, :image2, :image3)
    end
end

SalvemosVidasApp/app/helpers/slides_helper.rb
module SlidesHelper
end

SalvemosVidasApp/app/views/slides/_form.html.erb
<p id="notice"><%= notice %></p>
<%= form_with(model: @slide, local: true) do |form| %>
  <% if slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div id="formDatos" class="form-horizontal">
    <div id="formInput">

      <div class="form-group">
        <%= form.label :Titulo, class:"control-label col-sm-2"%>
        <div class="col-sm-8">
          <%= form.text_field :title, class:"form-control",placeholder:"Ingrese el dato..." %>
        </div>
      </div>

      <div class="container" align="center"> 
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <div class="item active">
              <%= image_tag("Diapositivas/tipo1.png", class:"img-responsive img-home") %>
              <div class="carousel-caption">
                <h3 style="background-color: rgba(255, 255, 255, 0.50); color: #000">Tipo 1</h3>
              </div>
            </div>

            <div class="item">
              <%= image_tag("Diapositivas/tipo2.png", class:"img-responsive img-home") %>
              <div class="carousel-caption">
                <h3 style="background-color: rgba(255, 255, 255, 0.50); color: #000">Tipo 2</h3>
              </div>
            </div>
          
            <div class="item">
              <%= image_tag("Diapositivas/tipo3.png", class:"img-responsive img-home") %>
              <div class="carousel-caption">
                <h3 style="background-color: rgba(255, 255, 255, 0.50); color: #000">Tipo 3</h3>
              </div>
            </div>
            <div class="item">
              <%= image_tag("Diapositivas/tipo4.png", class:"img-responsive img-home") %>
              <div class="carousel-caption">
                <h3 style="background-color: rgba(255, 255, 255, 0.50); color: #000">Tipo 4</h3>
              </div>
            </div>
            <div class="item">
              <%= image_tag("Diapositivas/tipo5.png", class:"img-responsive img-home") %>
              <div class="carousel-caption">
                <h3 style="background-color: rgba(255, 255, 255, 0.50); color: #000">Tipo 5</h3>
              </div>
            </div>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev" style="background: transparent;">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next" style="background: transparent;">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

      <br>

      <div class="form-group">
        <%= form.label :tipo, class:"control-label col-sm-2"%>
        <div class="col-sm-8">
          <select class="form-control" name="slide[tipo]" id="slide_tipo" onchange="myFunction()" >
              <option value="tipo1">Tipo 1</option>
              <option value="tipo2">Tipo 2</option>
              <option value="tipo3">Tipo 3</option>
              <option value="tipo4">Tipo 4</option>
              <option value="tipo5">Tipo 5</option>
          </select>
          
        </div>
      </div>

      <div class="form-group" id="divParrafo1">
        <%= form.label :"Parrafo #1", class:"control-label col-sm-2"%>
        <div class="col-sm-8">
          <%= form.text_field :parrafo1, class:"form-control",placeholder:"Ingrese el dato..." %>
        </div>
      </div>

      <div class="form-group" id="divParrafo2" style="display: none;">
        <%= form.label :"Parrafo #2", class:"control-label col-sm-2"%>
        <div class="col-sm-8">
          <%= form.text_field :parrafo2, class:"form-control",placeholder:"Ingrese el dato..." %>
        </div>
      </div>

      <div class="form-group" id="divParrafo3" style="display: none;">
        <%= form.label :"Parrafo #3", class:"control-label col-sm-2"%>
        <div class="col-sm-8">
          <%= form.text_field :parrafo3, class:"form-control",placeholder:"Ingrese el dato..." %>
        </div>
      </div>

      <div class="form-group" id="divImagen1">
        <%= form.label :"Imagen #1", class:"control-label col-sm-2"%>
        <div class="col-sm-8">
          <%= form.file_field :image1, class:"form-control-file" %>
        </div>
      </div>

      <div class="form-group" id="divImagen2" style="display: none;">
        <%= form.label :"Imagen #2", class:"control-label col-sm-2"%>
        <div class="col-sm-8">
          <%= form.file_field :image2,class:"form-control-file" %>
        </div>
      </div>

      <div class="form-group" id="divImagen3" style="display: none;">
        <%= form.label :"Imagen #3", class:"control-label col-sm-2"%>
        <div class="col-sm-8">   
          <%= form.file_field :image3, class:"form-control-file" %>
        </div>
      </div>

      <div class="actions">
        <div class="col-sm-offset-2 col-sm-10">
          <%= form.submit "Guardar",name: "boton", class:"btn"%> <%= link_to "Terminar","/lessons/category/all",class:"btn"%>
        </div>
      </div>

    </div>   
  </div>
  
<% end %>

SalvemosVidasApp/app/views/slides/edit.html.erb
<h1>Editing Slide</h1>

<%= render 'form', slide: @slide %>

<%= link_to 'Show', @slide %> |
<%= link_to 'Back', slides_path %>

SalvemosVidasApp/app/views/slides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slides</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Lesson</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.title %></td>
        <td><%= slide.tipo %></td>
        <td><%= slide.lesson %></td>
        <td><%= link_to 'Show', slide %></td>
        <td><%= link_to 'Edit', edit_slide_path(slide) %></td>
        <td><%= link_to 'Destroy', slide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide', new_slide_path %>

SalvemosVidasApp/app/views/slides/new.html.erb
<div class="container" style="background: #fafafa; width: 95%; height: 90%; padding-bottom: 20px;">
	<h2 align="center">Nueva Diapositiva</h2>

	<%= render 'form', slide: @slide %>

</div>

SalvemosVidasApp/app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @slide.title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @slide.tipo %>
</p>

<p>
  <strong>Lesson:</strong>
  <%= @slide.lesson %>
</p>

<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>